@startuml

Creator <|.. ConcreteCreator1
Creator <|.. ConcreteCreator2

Product <|.. ConcreteProduct1
Product <|.. ConcreteProduct2

Creator ..> Product : Product* = FactoryMethod()

interface Product{
    Operation()
}
class ConcreteProduct1{
   Operation()
}

class ConcreteProduct2{
   Operation()
}

interface Creator {
    Product* FactoryMethod()
    SomeOperation()
}

class ConcreteCreator1 {
    Product* FactoryMethod()
}

class ConcreteCreator2 {
    Product* FactoryMethod()
}


@enduml