@startuml
' https://plantuml.com/  online server

class 氧气
class 水

class 动物{
    - 有生命
    + 新陈代谢(氧气,水)
    - 繁殖()

}
class 鸟{
    - 羽毛
    + 下蛋()
}


class 翅膀
class 气候
class 雁群{
    + V形飞行()
    + 一形飞行()
}


class 大雁
class 鸭
class 企鹅
class 唐老鸭


大雁    : 飞()
大雁    : 下蛋()
鸭      : 下蛋()
企鹅    : 下蛋()
唐老鸭  : 讲话()

interface 飞翔
飞翔    : 飞()

@enduml