@startuml

Client --> Singleton: Singleton*=Singleton::GetInstance()

class Singleton{
    # {static} singleton_
    # Singleton(std::string)
    # value_
    + <del>Singleton(&) </del>
    + <del>Singleton=(&) </del>
    + {static} GetInstance(): Singleton *
}

@enduml