@startuml

title decoration: problem  restrict  solution

' boost design pattern: https://theboostcpplibraries.com/design-patterns

note left of 宜居住房: Bridge 桥接模式

住户 --> 宜居住房

宜居住房 <|.. 舒适住房
宜居住房 o--  功能改造
功能改造 <|.. 初级改造
功能改造 <|.. 系统改造

interface 宜居住房{
    - 功能改造
    + 智能()
    + 收纳()
    + 整洁()
}

class 舒适住房{
    + 空间()
    + 动线()
}

interface 功能改造{
    + 水()
    + 电()
    + 家具()
    + 电器()
}

class 初级改造{
}

class 系统改造{
}


住户 --> 智能家居
note left of 智能家居: Facade 外观模式


interface 智能家居{
    + 设备控制(开关, 延时, 其他)
}

class 小爱同学{
    + 设备连接()
    + 设备控制(开关, 延时, 其他)
}

智能家居 <|.. 小爱同学

小爱同学 ..> 灯具
小爱同学 ..> 浴霸
小爱同学 ..> 晾衣架
小爱同学 ..> 密码锁

灯具   : 手动控制()
浴霸   : 手动控制()
晾衣架 : 手动控制()
密码锁 : 手动控制()
灯具   : WIFI控制()
浴霸   : WIFI控制()
晾衣架 : WIFI控制()
密码锁 : WIFI控制()


住户 --> 收纳整理
note left of 收纳整理: Composite 组合模式

收纳整理 <|.. 收纳整理min
收纳整理 <|.. 收纳组合
收纳整理 --o  收纳组合

interface 收纳整理{
    + 收纳()
}

class 收纳整理min{
    + 收纳()
}

class 收纳组合{
    - children: 收纳整理[]
    + add(收纳整理)
    + remove(收纳整理)
    + getChildren():收纳整理[]
    + 收纳()
}

住户 --> 水
note left of 水: Proxy 代理模式

水 <|.. 自来水
水 <|.. 净水
自来水 --o 净水

interface 水{
    + 出水()
}

class 自来水{
    + 出水()
}

class 净水{
    - 水源: 自来水
    + 净水(自来水)
    + 出水()
}


住户 --> 电
note left of 电:  Adaptor 适配模式

电     <|..   插座
插座     -->  电力服务

interface  电{
    + 插电(电压,插头)
}

class 插座{
    - 电源: 电力服务
    + 电力适配(电压,插头)
    + 插电(电压,插头)
}

class 电力服务{
    - type: 220V交流
    + 国标供电()
}


住户 --> 食品
note left of 食品: Decorator 装饰模式


食品    <|.. 餐品
食品    <|.. 食品装盘
食品    --o  食品装盘

食品装盘 <|-- 冷菜装盘
食品装盘 <|-- 热菜装盘
食品装盘 <|-- 配菜装盘

interface 食品{
    + 吃()
}

class 餐品{
    + 吃()
}

class 食品装盘{
    - 来源: 食品
    + 食品装盘(食品)
    + 吃()
}

class 冷菜装盘{
    - 来源: 食品
    + 冷菜装盘(食品)
    + 吃()
}

class 热菜装盘{
    - 来源: 食品
    + 热菜装盘(食品)
    + 吃()
}

class 配菜装盘{
    - 来源: 食品
    + 配菜装盘(食品)
    + 吃()
}

@enduml